"""empty message

Revision ID: 102d962b5ae8
Revises: 200555d60163
Create Date: 2022-11-22 22:25:05.407146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102d962b5ae8'
down_revision = '200555d60163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=False)

    # ### end Alembic commands ###
