"""empty message

Revision ID: 200555d60163
Revises: 56dc8b3f8499
Create Date: 2022-11-22 21:55:06.859967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200555d60163'
down_revision = '56dc8b3f8499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
